### ISSUE TITLE
support for Arduino CLI 1. x?

### ISSUE THREAD

**Issue by VirensCn** [vscode-arduino/vscode-arduino#10]
Microsoft's [VS Code Arduino Extension Deprecation](https://github.com/microsoft/vscode-arduino/issues/1757). Is the Community Edition considering providing support for Arduino CLI 1.x in the future?

**Comment by VirensCn** [comment]
Currently, it has been found that ESP32 is unable to generate `c_cpp_properties.json` file.

ESP32 version: 3.0.4
ardunio-cli: 1.0.4

**Comment by ParadoxV5** [comment]
* Supercedes microsoft/vscode-arduino#1749
