### ISSUE TITLE
Question: How to enable verbose output for compile and flash when using ArduinoCLI?

### ISSUE THREAD

**Issue by beegee-tokyo** [vscode-arduino/vscode-arduino#36]
I am using ArduinoCLI, installed by myself. the path is set correct. I setup arduino-cli.yaml file.

When using the "original" Arduino extension, I saw during compile and flashing all outputs. 

How do I enable it with the community edition?

**Comment by SloMusti** [comment]
Set Arduino: Log Level in Vscode extension settings.

![image](https://github.com/user-attachments/assets/c6921a16-6ba9-4e58-b248-d66f67ff34c9)

**Comment by beegee-tokyo** [comment]
👍
