### ISSUE TITLE
Use newer Cocopa to handle more advanced GCC inclusion parameters

### ISSUE THREAD

**Issue by stigpo** [vscode-arduino/vscode-arduino#38]
Cocopa is not able to parse the inclusion logic used with RP Pico SDK and this causes pain for the developers when Intellisense is updated. A solution to this problem has been available since 2023 and I propose that we use the forked version of Cocopa until we can get the original developer to make the fix:

In packages.json use this for cocopa:
    "cocopa": "github:tylerjwatson/cocopa#semver:^0.0.15",

**Comment by lersi** [comment]
Merged your pull request, thank you very much for your contribution!
