### ISSUE TITLE
F1 - Arduino Board Manager does not work

### ISSUE THREAD

**Issue by roblatour** [vscode-arduino/vscode-arduino#58]
when I press F1 - and click on Arduino Board Manager nothing happens.

other points of context:

1.  F1 - Select Serial Port works fine.

2.  when I start Visual Studio Code I see the following in the Output tab:

           [Starting] Update package index files...
           dummy
           [Error] Exit with code=undefined

 3.  if in the Terminal tab I enter:
       & "C:\\Program Files\\Arduino IDE\\resources\\app\\lib\\backend\\resources\\arduino-cli.exe" core update-index
       I see:
       Downloading index: package_index.tar.bz2 downloaded
       but that is it

**Comment by marc-dantas** [comment]
What did you do to solve this problem? I'm having the exact same problem.

**Comment by roblatour** [comment]
Hi Marc, I don't believe I actually resolve it, rather I found another vs code extension that worked and started using it instead.  

As a result, I simply closed this issue here.

If you're interested, the other extension is here: https://marketplace.visualstudio.com/items?itemName=TheLastOutpostWorkshop.arduino-maker-workshop
